- name: bug
  color: "156511"
  description: Something isn't working
- name: bug1
  color: d73a4b
  description: Something isn't working
- name: bug2
  color: d73a4b
  description: Something isn't working
- name: bug3
  color: d73a4b
  description: Something isn't working
- name: bug4
  color: d73a4b
  description: Something isn't working
- name: bug5
  color: d73a4b
  description: Something isn't working
- name: documentation
  color: 0075cb
  description: Improvements or additions to documentation
- name: documentation1
  color: 0075cb
  description: Improvements or additions to documentation
- name: documentation2
  color: 0075cb
  description: Improvements or additions to documentation
- name: documentation3
  color: 0075cb
  description: Improvements or additions to documentation
- name: documentation4
  color: 0075cb
  description: Improvements or additions to documentation
- name: documentation5
  color: 0075cb
  description: Improvements or additions to documentation
- name: duplicate
  color: cfd3db
  description: This issue or pull request already exists
- name: duplicate1
  color: cfd3db
  description: This issue or pull request already exists
- name: duplicate2
  color: cfd3db
  description: This issue or pull request already exists
- name: duplicate3
  color: cfd3db
  description: This issue or pull request already exists
- name: duplicate4
  color: cfd3db
  description: This issue or pull request already exists
- name: duplicate5
  color: cfd3db
  description: This issue or pull request already exists
- name: enhancement
  color: a2eeeb
  description: New feature or request
- name: enhancement1
  color: a2eeeb
  description: New feature or request
- name: enhancement2
  color: a2eeeb
  description: New feature or request
- name: enhancement3
  color: a2eeeb
  description: New feature or request
- name: enhancement4
  color: a2eeeb
  description: New feature or request
- name: enhancement5
  color: a2eeeb
  description: New feature or request
- name: good first issue
  color: 7057fb
  description: Good for newcomers
- name: good first issue1
  color: 7057fb
  description: Good for newcomers
- name: good first issue2
  color: 7057fb
  description: Good for newcomers
- name: good first issue3
  color: 7057fb
  description: Good for newcomers
- name: good first issue4
  color: 7057fb
  description: Good for newcomers
- name: good first issue5
  color: 7057fb
  description: Good for newcomers
- name: help wanted
  color: "008672"
  description: Extra attention is needed
- name: help wanted1
  color: "008672"
  description: Extra attention is needed
- name: help wanted2
  color: "008672"
  description: Extra attention is needed
- name: help wanted3
  color: "008672"
  description: Extra attention is needed
- name: help wanted4
  color: "008672"
  description: Extra attention is needed
- name: help wanted5
  color: "008672"
  description: Extra attention is needed
- name: invalid
  color: e4e669
  description: This doesn't seem right
- name: invalid1
  color: e4e669
  description: This doesn't seem right
- name: invalid2
  color: e4e669
  description: This doesn't seem right
- name: invalid3
  color: e4e669
  description: This doesn't seem right
- name: invalid4
  color: e4e669
  description: This doesn't seem right
- name: invalid5
  color: e4e669
  description: This doesn't seem right
- name: question
  color: d876e3
  description: Further information is requested
- name: question1
  color: d876e3
  description: Further information is requested
- name: question2
  color: d876e3
  description: Further information is requested
- name: question3
  color: d876e3
  description: Further information is requested
- name: question4
  color: d876e3
  description: Further information is requested
- name: question5
  color: d876e3
  description: Further information is requested
- name: wontfix
  color: ffffff
  description: This will not be worked on
- name: wontfix1
  color: ffffff
  description: This will not be worked on
- name: wontfix2
  color: ffffff
  description: This will not be worked on
- name: wontfix3
  color: ffffff
  description: This will not be worked on
- name: wontfix4
  color: ffffff
  description: This will not be worked on
- name: wontfix5
  color: ffffff
  description: This will not be worked on
