//  Same deal as before but this was generated by **cargo**
fn main() {
    println!("Hello, cargo!");
}

/*
 Create a new project using `cargo new <project_name>`
 Build using `cargo build`. You can run the executable as before
 Use `cargo run` to compile and run the code in one command
 Using `cargo check` compiles your code but doesn't execute it
 When building for release use the `cargo build --release` flag to compile with optimizations.
*/

//  Cargo.toml is cargo's configuration file. akin to package.json in the node world
